//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
namespace ElementProperties
{
	public enum Nation
	{ 
		Fire, Water, Earth, Air
	}
	public class Element{
		private Nation nation;
		//private GameObject projectile_skill;
		
		public Element(int n_4){
			switch(n_4 % 4){
			case 0:
				this.nation = Nation.Fire;
				//projectile_skill = (GameObject)Resources.Load("FireBend", typeof(GameObject));
				break;
			case 1:
				this.nation = Nation.Water;
				//projectile_skill = (GameObject)Resources.Load("WaterBend", typeof(GameObject));
				break;
			case 2:
				this.nation = Nation.Earth;
				//projectile_skill = (GameObject)Resources.Load("EarthBend", typeof(GameObject));
				break;
			case 3:
				this.nation = Nation.Air;
				//projectile_skill = (GameObject)Resources.Load("AirBend", typeof(GameObject));
				break;
			}
		}

		public Nation getNation(){
			return this.nation;
		}


	}

}

